name: ai_kladovshchik
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.7.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_app_check: ^0.2.0+1
  excel: ^2.1.0
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-dir: lib/l10n

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"